import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { motion } from '../framer-motion'
import Script from 'next/script'
import { useRouter } from 'next/router'
const Home: NextPage = () => {
  const router = useRouter();
  const forceReload = () => {
    router.reload();
  }
  return (

    <div className={styles.container}>
      <Head>
        <title>Home of the Unstable</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/webIcon.ico" />
      </Head>

      <Script strategy='afterInteractive' id="mainScript-HU" src="/mainScript.js"
       onError={(e) => {
        console.error('Script failed to load', e)
      }} >
      </Script>

      
      <motion.div initial="hidden" animate="visible" className={styles.shutter} variants={{
            hidden: {
                x: -720,
                scaleX: 1.5
            },
            visible:{
                scaleX: 0,
                x: -1870,
                transition: {
                    delay: 2,
                    duration: 3,
                    ease: [0.075, 0.32, 0.05, 1]
                }
            }
        }}> 
      </motion.div>
        
      <motion.div initial="hidden" animate="visible" className={styles.shutter} variants={{
            hidden: {
                x: 720,
                scaleX: 1.5
            },
            visible:{
                scaleX: 0,
                x: 1870,
                transition: {
                  delay: 2,
                  duration: 3,
                  ease: [0.075, 0.32, 0.05, 1]
                }
            }
        }}> 
      </motion.div>

      <motion.div initial="hidden" animate="visible" variants={{
            hidden: {
                x: 0,
            },
            visible:{
                x: 80,
                transition: {
                  delay: 2,
                  duration: 1,
                  ease: [0.075, 0.32, 0.2, 1]
                }
            }
        }}> 

        <motion.div initial="hidden" animate="visible" className={styles.shutterLine} variants={{
            hidden: {
                scaleY: 0.1,
                y: -700
            },
            visible:{
                scaleY: 1,
                y: 0,
                transition: {
                  delay: 1,
                  duration: 1,
                  ease: [0.075, 0.32, 0.2, 1]
                }
            }
            
        }}> 
        </motion.div>

      </motion.div>

      <main className={styles.main}>

        <motion.div initial="hidden" animate="visible" whileHover={{
          scale: 1.1
        }}> 
          <Link href='/'>
            <a onClick={(e) => forceReload()}>
              <Image src='/images/webIcon.ico' className={styles.hu_Logo} width={400} height={400}></Image>
            </a>
          </Link>
        </motion.div>
        
        <motion.div initial="hidden" animate="visible" whileHover={{
            scale: 1.2
        }}>
          <h1 className={styles.moving_background_gradient}>
              Home of the Unstable
          </h1>
        </motion.div>
      </main>
      <main className={styles.main2}>
        <div className={styles.monitorScreenImage}>
        <Image src='/images/HUScreen.gif' alt='monitorScreen' className={styles.monitorScreenImage} width={990} height={200}></Image>
        </div>
        <p className={styles.monitorLinks}>
          <a href='https://www.roblox.com/users/2680507685/profile' className={styles.gridLinks}>
          LOLOLOLOLOLOL
          </a>
          <a href='https://www.roblox.com/users/2977283018/profile' className={styles.gridLinks}>
          LOLOLOLOLOLOL
          </a>
          <a className={styles.gridLinks}>
          LOLOLOLOLOLOL
          </a>
          <a className={styles.gridLinks}>
          LOLOLOLOLOLOL
          </a>
        </p>

        <div className={styles.pocketWatch}>
        <Image src='/images/BrokenPocketWatch.png' width={300} height={300} className={styles.pocketWatch}></Image>
        </div>

      </main>
      
      <footer className={styles.footer}>
        <h3>
          ©2022 by Mise
        </h3>
      </footer>
    </div>
  )
}

export default Home
